/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logicanebulosa;

import java.awt.Toolkit;

/**
 *
 * @author aluno
 */
public class VIEW extends javax.swing.JFrame {

    public VIEW() {
        initComponents();
        initCombo();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(VIEW.class.getResource("iconApp.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAvaliacao = new javax.swing.JPanel();
        cboComida = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboService = new javax.swing.JComboBox<>();
        btnAvaliacao = new javax.swing.JButton();
        lblIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurante do povo");
        getContentPane().setLayout(null);

        cboComida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "péssima", "comível", "deliciosa" }));

        jLabel1.setText("Qualidade da comida");

        jLabel2.setText("Qualidade do serviço");

        cboService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "ruim", "aceitável", "excelente" }));

        btnAvaliacao.setText("Avaliar");
        btnAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAvaliacaoLayout = new javax.swing.GroupLayout(panelAvaliacao);
        panelAvaliacao.setLayout(panelAvaliacaoLayout);
        panelAvaliacaoLayout.setHorizontalGroup(
            panelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAvaliacaoLayout.createSequentialGroup()
                .addGroup(panelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAvaliacaoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(cboComida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboService, 0, 211, Short.MAX_VALUE)))
                    .addGroup(panelAvaliacaoLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnAvaliacao)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelAvaliacaoLayout.setVerticalGroup(
            panelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAvaliacaoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnAvaliacao)
                .addContainerGap())
        );

        getContentPane().add(panelAvaliacao);
        panelAvaliacao.setBounds(50, 120, 280, 210);

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logicanebulosa/food-1050813_1280.jpg"))); // NOI18N
        lblIcon.setText("jLabel1");
        getContentPane().add(lblIcon);
        lblIcon.setBounds(-10, 0, 430, 480);

        setSize(new java.awt.Dimension(400, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliacaoActionPerformed
        if (cboComida.getSelectedIndex() == 0) {

        } else if (cboService.getSelectedIndex() == 0) {

        } else {
            avaliarGorjeta();
        }
    }//GEN-LAST:event_btnAvaliacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvaliacao;
    private javax.swing.JComboBox<String> cboComida;
    private javax.swing.JComboBox<String> cboService;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JPanel panelAvaliacao;
    // End of variables declaration//GEN-END:variables

    private void initCombo() {
    }

    private void avaliarGorjeta() {
        if(cboComida.getSelectedIndex() == 3 || cboService.getSelectedIndex() == 3){
            System.out.println("Gorjeta alta");
        } else if (cboService.getSelectedIndex() == 2){
            System.out.println("Gorjeta média");
        } else if(cboComida.getSelectedIndex()== 0 && cboService.getSelectedIndex()== 0){
            System.out.println("Gorjeta baixa");
        } else{
            System.out.println("Gorjeta baixa");
        }
    }
}
