/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class VIEW extends javax.swing.JFrame {

    public VIEW() {
        initComponents();
        initCombo();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(VIEW.class.getResource("/image/iconApp.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGarcom = new javax.swing.JPanel();
        lblGarcom = new javax.swing.JLabel();
        lblGorjeta = new javax.swing.JLabel();
        panelAvaliacao = new javax.swing.JPanel();
        cboComida = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboService = new javax.swing.JComboBox<>();
        btnAvaliacao = new javax.swing.JButton();
        panelHeader = new javax.swing.JPanel();
        lblIconPanel = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurante do povo");
        setResizable(false);
        getContentPane().setLayout(null);

        panelGarcom.setBackground(new java.awt.Color(162, 100, 100));

        lblGarcom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/waiter_7315375.png"))); // NOI18N

        lblGorjeta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGorjeta.setForeground(new java.awt.Color(255, 255, 255));
        lblGorjeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelGarcomLayout = new javax.swing.GroupLayout(panelGarcom);
        panelGarcom.setLayout(panelGarcomLayout);
        panelGarcomLayout.setHorizontalGroup(
            panelGarcomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGarcomLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblGarcom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGorjeta, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        panelGarcomLayout.setVerticalGroup(
            panelGarcomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGarcomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGarcomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGarcom, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lblGorjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelGarcom);
        panelGarcom.setBounds(110, 410, 170, 40);

        panelAvaliacao.setBackground(new java.awt.Color(111, 64, 64));

        cboComida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "péssima", "comível", "deliciosa" }));
        cboComida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboComidaKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Qualidade da comida");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Qualidade do serviço");

        cboService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "ruim", "aceitável", "excelente" }));

        btnAvaliacao.setBackground(new java.awt.Color(58, 58, 58));
        btnAvaliacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAvaliacao.setForeground(new java.awt.Color(255, 255, 255));
        btnAvaliacao.setText("Avaliar");
        btnAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliacaoActionPerformed(evt);
            }
        });

        panelHeader.setBackground(new java.awt.Color(162, 100, 100));

        lblIconPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconApp.png"))); // NOI18N

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblIconPanel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblIconPanel)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAvaliacaoLayout = new javax.swing.GroupLayout(panelAvaliacao);
        panelAvaliacao.setLayout(panelAvaliacaoLayout);
        panelAvaliacaoLayout.setHorizontalGroup(
            panelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAvaliacaoLayout.createSequentialGroup()
                .addGroup(panelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAvaliacaoLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnAvaliacao))
                    .addGroup(panelAvaliacaoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(cboComida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboService, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(36, Short.MAX_VALUE))
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelAvaliacaoLayout.setVerticalGroup(
            panelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAvaliacaoLayout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnAvaliacao)
                .addGap(27, 27, 27))
        );

        getContentPane().add(panelAvaliacao);
        panelAvaliacao.setBounds(50, 100, 280, 250);

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/food-1050813_1280.jpg"))); // NOI18N
        lblIcon.setText("jLabel1");
        getContentPane().add(lblIcon);
        lblIcon.setBounds(-10, 0, 430, 520);

        setSize(new java.awt.Dimension(400, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliacaoActionPerformed
        if (cboComida.getSelectedIndex() == 0) {
            cboComida.setBackground(Color.red);
        } else if (cboService.getSelectedIndex() == 0) {
            cboService.setBackground(Color.red);
        } else if(JOptionPane.showConfirmDialog(this, "Deseja Avaliar?","Avaliação",JOptionPane.YES_NO_OPTION) == 0) {
            configurarComboBox();
            avaliarGorjeta();
        }
    }//GEN-LAST:event_btnAvaliacaoActionPerformed

    private void cboComidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboComidaKeyPressed

    }//GEN-LAST:event_cboComidaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvaliacao;
    private javax.swing.JComboBox<String> cboComida;
    private javax.swing.JComboBox<String> cboService;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblGarcom;
    private javax.swing.JLabel lblGorjeta;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIconPanel;
    private javax.swing.JPanel panelAvaliacao;
    private javax.swing.JPanel panelGarcom;
    private javax.swing.JPanel panelHeader;
    // End of variables declaration//GEN-END:variables

    private void initCombo() {
    }

    private void avaliarGorjeta() {
        if (cboComida.getSelectedIndex() == 3 || cboService.getSelectedIndex() == 3) {
            lblGorjeta.setText("Gorjeta alta");
        } else if (cboService.getSelectedIndex() == 2) {
            lblGorjeta.setText("Gorjeta média");
        } else if (cboComida.getSelectedIndex() == 0 && cboService.getSelectedIndex() == 0) {
            lblGorjeta.setText("Gorjeta baixa");
        } else {
            lblGorjeta.setText("Gorjeta baixa");
        }
    }

    private void configurarComboBox() {
        cboComida.setBackground(null);
        cboService.setBackground(null);
    }
}
